const assert = require('node:assert/strict');
const { purchaseCompletion } = require('../indentCompletion');
const date = '2026-09-18 10:00:00';
const items = [{ id: 1, quantity: 10 }, { id: 2, quantity: 5 }];
const pos = [{ id: 1, total_amount: 100, po_l1_at: date, po_l2_at: date, created_at: date }];
const lines = [{ id: 1, vendor_po_id: 1, indent_item_id: 1, quantity: 10 }, { id: 2, vendor_po_id: 1, indent_item_id: 2, quantity: 5 }];
const rates = items.map(i => ({ indent_item_id: i.id, status: 'finalized', final_rate: 10, finalized_at: date }));
const note = entries => ({ vendor_po_id: 1, status: 'received', document_type: 'challan', received_at: date, created_at: date, items_json: JSON.stringify(entries) });
const entries = lines.map(l => ({ vendor_po_item_id: l.id, quantity: l.quantity, received_qty: l.quantity }));
const run = (changes = {}) => purchaseCompletion(changes.items || items, changes.pos || pos, changes.lines || lines, changes.rates || rates, changes.notes || [note(entries)], changes.bills || [{ vendor_po_id: 1, total_amount: 100, created_at: date }]);
assert.equal(run().dispatch, date);
assert.equal(run().received, date);
assert.equal(run().purchase_bill, date);
assert.equal(run({ rates: rates.slice(0, 1) }).rates, null);
assert.equal(run({ lines: lines.slice(0, 1) }).po_l1, null);
assert.equal(run({ lines: lines.map(l => ({ ...l, quantity: 1 })) }).dispatch, null);
assert.equal(run({ pos: [{ ...pos[0], cancelled: 1 }] }).received, null);
assert.equal(run({ notes: [note(entries.slice(0, 1))] }).dispatch, null);
assert.equal(run({ notes: [note(entries.map(e => ({ ...e, received_qty: 1 })))] }).received, null);
assert.equal(run({ notes: [{ ...note(entries), is_draft: 1 }] }).dispatch, null);
assert.equal(run({ notes: [{ ...note(entries), document_type: 'sales_bill' }] }).dispatch, null);
assert.equal(run({ notes: [{ ...note(entries), items_json: 'invalid' }] }).dispatch, null);
assert.equal(run({ bills: [{ vendor_po_id: 1, total_amount: 20, created_at: date }] }).purchase_bill, null);
assert.equal(run({ items: [...items, { id: 3, source: 'store', quantity: 99 }, { id: 4, quantity: 0 }] }).rates, date);
assert.equal(run({ items: [...items, { id: 3, source: 'store', quantity: 99 }] }).dispatch, null);
const stock = [{ id: 3, source: 'store', stock_issue_note_id: 7, description: 'Cable', unit: 'm', quantity: 10 }];
const stockNote = { stock_issue_note_id: 7, document_type: 'challan', status: 'received', received_at: date, created_at: date, items_json: JSON.stringify([{ description: 'Cable', unit: 'm', qty: 10 }]) };
assert.equal(run({ items: stock, pos: [], lines: [], notes: [stockNote] }).received, date);
assert.equal(run({ items: stock, pos: [], lines: [], notes: [{ ...stockNote, status: 'partial' }] }).received, null);
assert.equal(run({ items: stock, pos: [], lines: [], notes: [{ ...stockNote, items_json: JSON.stringify([{ description: 'Other', unit: 'm', qty: 100 }]) }] }).dispatch, null);
const partial = entries.map(e => ({ ...e, quantity: e.quantity / 2, received_qty: e.received_qty / 2 }));
assert.equal(run({ notes: [note(partial), note(partial)] }).received, date);
assert.equal(run({ pos: [...pos, { id: 2, po_l1_at: null }] }).po_l1, null);
console.log('Indent completion regression checks passed');
