import {useEffect,useState} from 'react';
import api from '../api';
import Modal from './Modal';
import toast from 'react-hot-toast';
import {useAuth} from '../context/AuthContext';
const rupees=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const today=()=>new Date(Date.now()+19800000).toISOString().slice(0,10);
const blankRules={mode:'rolling',amount_limit:'',payment_days:'',client_email:'',owner_id:'',pm_id:'',head_id:''};
export default function RaBillingBoard(){
  const {canApprove,canEdit,canCreate}=useAuth();
  const [data,setData]=useState({queue:[],bills:[],users:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [settings,setSettings]=useState(null),[rules,setRules]=useState(blankRules),[detail,setDetail]=useState(null);
  const [kind,setKind]=useState('measurement'),[submission,setSubmission]=useState({submitted_on:today(),reference:'',submission_proof:''});
  const [signed,setSigned]=useState({signed_on:today(),path:''}),[payment,setPayment]=useState({amount:'',payment_date:today(),payment_mode:'Bank',transaction_ref:''});
  const load=async()=>{try{setData((await api.get('/sales-billing/ra')).data);setError('');}catch(e){setError(e.response?.data?.error||'Could not load RA billing');}};
  useEffect(()=>{load();},[]);
  const openBill=async id=>{setDetail((await api.get(`/sales-billing/ra/bills/${id}`)).data);setSubmission({submitted_on:today(),reference:'',submission_proof:''});setSigned({signed_on:today(),path:''});};
  const action=async(fn,message)=>{setBusy(true);try{await fn();toast.success(message);await load();if(detail)setDetail((await api.get(`/sales-billing/ra/bills/${detail.bill.id}`)).data);}catch(e){toast.error(e.response?.data?.error||e.message||'Action failed');}finally{setBusy(false);}};
  const upload=async file=>{if(!file)throw Error('Choose a file');const form=new FormData();form.append('file',file);return (await api.post('/upload',form)).data;};
  const configure=async id=>{try{const r=(await api.get(`/sales-billing/ra/rules/${id}`)).data;setRules({...blankRules,...Object.fromEntries(Object.entries(r).map(([k,v])=>[k,v??'']))});setSettings(id);}catch{toast.error('Could not load settings');}};
  const download=async id=>{
    try{const response=await api.get(`/sales-billing/ra/bills/${id}/pack`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`RA-${id}-pack.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){let message='Complete measurements, report and photos before downloading';try{message=JSON.parse(await e.response.data.text()).error;}catch{}toast.error(message);}
  };
  const totals=data.queue.reduce((a,g)=>({approved:a.approved+g.approved_value,pending:a.pending+g.pending_value,due:a.due+g.eligible_value}),{approved:0,pending:0,due:0});
  return <div className="space-y-4">
    <div className="rounded-xl bg-blue-50 border border-blue-200 p-4"><h3 className="font-semibold">RA billing · SOP-13</h3><p className="text-sm mt-1">Daily work → 15 days or amount limit → complete bill pack → submission → signed copy → collection. Rejected DPRs are excluded.</p></div>
    {error&&<div role="alert" className="text-red-700">{error}<button className="btn ml-2" onClick={load}>Retry</button></div>}
    <div className="grid sm:grid-cols-3 gap-3">{[['Approved work, unbilled',totals.approved],['Work awaiting DPR approval',totals.pending],['Eligible to bill now',totals.due]].map(([label,value])=><div key={label} className="card p-4"><div className="text-sm text-gray-500">{label}</div><strong className="text-xl">{rupees(value)}</strong></div>)}</div>
    <div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">Daily unbilled work · installation portion, before GST</h4><button disabled={busy||!canCreate('installation')||!data.queue.some(g=>g.eligible_ids.length)} className="btn btn-primary" onClick={()=>action(()=>api.post('/sales-billing/ra/generate'),'Eligible RA bills created')}>Create eligible bills</button></div>
    {!data.queue.length&&<p className="text-gray-500">No approved or pending unbilled DPRs.</p>}
    <div className="grid lg:grid-cols-2 gap-3">{data.queue.map(g=><div key={g.project_id} className="card p-4 space-y-2"><div className="flex justify-between gap-2"><strong>{g.project_name||g.customer}</strong><button className="text-blue-700 underline text-sm" onClick={()=>configure(g.project_id)}>Billing rules</button></div><p className="text-sm">{g.customer}</p><div className="grid grid-cols-2 gap-2 text-sm"><span>Approved: {rupees(g.approved_value)}</span><span>Awaiting approval: {rupees(g.pending_value)}</span><span>Oldest approved: {g.oldest_date||'—'}</span><span>Age: {g.age_days} days</span><span>Early limit: {g.rule.amount_limit?rupees(g.rule.amount_limit):'Not configured'}</span><span>Cycle: {g.rule.mode==='calendar'?'Half-month':'15 days from oldest work'}</span></div><p className={g.eligible_ids.length?'text-emerald-700 font-semibold':'text-gray-500'}>{g.trigger}</p><details><summary className="cursor-pointer text-sm">DPR breakdown ({g.dprs.length})</summary>{g.dprs.map(d=><p className="text-sm py-1" key={d.id}>DPR #{d.id} · {d.date} · {d.status} · {rupees(d.amount)}</p>)}</details></div>)}</div>
    <h4 className="font-semibold">Bill submission, signatures and collections</h4>
    <div className="grid lg:grid-cols-2 gap-3">{data.bills.map(b=><div className="card p-4 space-y-2" key={b.id}><strong>{b.bill_number}</strong><p className="text-sm">{b.project_name||b.customer_name} · {rupees(b.total_amount)}</p><p className="text-sm">{b.submitted_on?`Submitted ${b.submitted_on} · ${b.signed_on?`Signed ${b.signed_on}`:'Signature pending'}`:'Bill pack / submission pending'}</p>{b.submitted_on&&<p className="text-sm">Due {b.due_date} · Outstanding {rupees(b.outstanding_amount)} · {b.ageing_days||0} days overdue</p>}<div className="flex gap-3"><button className="btn btn-secondary" onClick={()=>openBill(b.id).catch(()=>toast.error('Could not open bill'))}>Bill pack & submission</button><button className="text-blue-700 text-sm underline" onClick={()=>configure(b.business_book_id)}>Billing rules</button></div></div>)}</div>
    <Modal isOpen={!!settings} onClose={()=>!busy&&setSettings(null)} title="Project billing rules"><div className="space-y-3">
      <label className="block text-sm">Billing cycle<select className="input w-full" value={rules.mode} onChange={e=>setRules({...rules,mode:e.target.value})}><option value="rolling">15 days from oldest approved unbilled work</option><option value="calendar">1st–15th / 16th–month-end</option></select></label>
      <label className="block text-sm">Early amount limit (₹, before GST; blank disables)<input className="input w-full" type="number" min="0.01" step="0.01" value={rules.amount_limit} onChange={e=>setRules({...rules,amount_limit:e.target.value})}/></label>
      <label className="block text-sm">Agreed payment days from submission<input className="input w-full" type="number" min="0" max="365" value={rules.payment_days} onChange={e=>setRules({...rules,payment_days:e.target.value})}/></label>
      <label className="block text-sm">Client billing email<input className="input w-full" type="email" value={rules.client_email} onChange={e=>setRules({...rules,client_email:e.target.value})}/></label>
      {[['owner_id','Day 3: Billing owner'],['pm_id','Day 5: Project Manager'],['head_id','Day 7: Head']].map(([key,label])=><label key={key} className="block text-sm">{label}<select className="input w-full" value={rules[key]} onChange={e=>setRules({...rules,[key]:e.target.value})}><option value="">Select responsible person</option>{data.users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label>)}
      <p className="text-xs text-gray-500">Follow-ups appear in ERP notifications once per stage until the signed copy is uploaded.</p>
      <button disabled={busy||!canApprove('installation')} className="btn btn-primary" onClick={()=>action(async()=>{await api.put(`/sales-billing/ra/rules/${settings}`,rules);setSettings(null);},'Billing rules saved')}>Save rules</button>
    </div></Modal>
    <Modal isOpen={!!detail&&!settings} onClose={()=>!busy&&setDetail(null)} title={`RA bill pack · ${detail?.bill.bill_number||''}`} xwide>{detail&&<div className="space-y-4">
      <div className="text-sm bg-blue-50 p-3 rounded">{detail.bill.project_name} · Total {rupees(detail.bill.total_amount)}. Submission starts payment ageing; uploading a signed copy does not reset it.</div>
      <div className="flex gap-3 flex-wrap">{['measurement','report','photo'].map(k=><span key={k} className="text-sm">{JSON.parse(detail.workflow.documents).some(d=>d.kind===k)?'✓':'○'} {k}</span>)}<button onClick={()=>download(detail.bill.id)} className="text-blue-700 underline">Download bill pack ZIP</button></div>
      {JSON.parse(detail.workflow.documents).map((d,i)=><div key={i} className="flex gap-3 text-sm"><a className="text-blue-700 underline" target="_blank" rel="noreferrer" href={d.path}>{d.kind}: {d.name}</a>{!detail.workflow.submitted_on&&<button disabled={busy||!canEdit('installation')} onClick={()=>action(()=>api.delete(`/sales-billing/ra/bills/${detail.bill.id}/documents/${i}`),'Attachment removed')}>Remove</button>}</div>)}
      {!detail.workflow.submitted_on&&<div className="border rounded p-3 space-y-3"><label className="block text-sm">Add bill-pack document<select className="input ml-2" value={kind} onChange={e=>setKind(e.target.value)}><option value="measurement">Measurement sheet</option><option value="report">Work report</option><option value="photo">Site photos</option></select></label><input aria-label="Upload bill pack document" type="file" disabled={busy||!canEdit('installation')} onChange={e=>{const f=e.target.files?.[0];if(f)action(async()=>{const r=await upload(f);await api.post(`/sales-billing/ra/bills/${detail.bill.id}/documents`,{kind,path:r.url,name:r.filename});},'Document attached');}}/>
      <details><summary>Linked DPR evidence</summary>{detail.dprs.map(d=><p className="text-sm" key={d.id}>DPR #{d.id} · {d.report_date} <a className="text-blue-700 underline" target="_blank" rel="noreferrer" href="/dpr">View Daily Reports</a></p>)}</details></div>}
      {!detail.workflow.submitted_on?<div className="border rounded p-3 space-y-3"><h4 className="font-semibold">Submit complete bill pack</h4><button className="text-blue-700 underline text-sm" onClick={()=>configure(detail.bill.business_book_id)}>Set client payment terms and follow-up owners</button><p className="text-sm">Email recipient: {detail.rule.client_email||'Not configured'}</p><button disabled={busy||!canEdit('installation')||['sending','sent'].includes(detail.workflow.mail_state)} className="btn btn-primary" onClick={()=>action(()=>api.post(`/sales-billing/ra/bills/${detail.bill.id}/email`),'Bill pack emailed and submission recorded')}>Email complete pack to client</button>
      {detail.workflow.mail_error&&<p className="text-red-700 text-sm">{detail.workflow.mail_error}. Check the mailbox and record evidence below; do not resend blindly.</p>}
      <p className="text-sm font-semibold">Or record a submission already made outside ERP</p><label className="block text-sm">Actual submission date<input type="date" className="input w-full" value={submission.submitted_on} onChange={e=>setSubmission({...submission,submitted_on:e.target.value})}/></label><label className="block text-sm">Submission reference<input className="input w-full" value={submission.reference} onChange={e=>setSubmission({...submission,reference:e.target.value})} placeholder="Client receipt / email reference"/></label><label className="block text-sm">Submission evidence<input type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)action(async()=>{const r=await upload(f);setSubmission(s=>({...s,submission_proof:r.url}));},'Evidence uploaded');}}/></label>{submission.submission_proof&&<p className="text-sm text-emerald-700">Evidence attached</p>}<button disabled={busy||!canEdit('installation')} className="btn btn-primary" onClick={()=>action(()=>api.post(`/sales-billing/ra/bills/${detail.bill.id}/submit`,submission),'Submission recorded; collection due date created')}>Record submission</button></div>:<div className="border rounded p-3 space-y-3"><p>Submitted {detail.workflow.submitted_on} · {detail.workflow.submission_reference}</p>{detail.workflow.signed_file?<a className="text-emerald-700 underline" href={detail.workflow.signed_file} target="_blank" rel="noreferrer">Signed copy · {detail.workflow.signed_on}</a>:<><label className="block text-sm">Client signing date<input className="input" type="date" value={signed.signed_on} onChange={e=>setSigned({...signed,signed_on:e.target.value})}/></label><input aria-label="Signed bill copy" type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)action(async()=>{const r=await upload(f);setSigned(s=>({...s,path:r.url}));},'Signed file uploaded');}}/><button disabled={busy||!signed.path||!canEdit('installation')} className="btn btn-primary" onClick={()=>action(()=>api.post(`/sales-billing/ra/bills/${detail.bill.id}/sign`,signed),'Signed copy recorded; reminders stopped')}>Save signed copy</button></>}
      <details><summary className="cursor-pointer font-semibold">Record collection against this RA bill</summary><div className="grid sm:grid-cols-2 gap-3 my-3"><label>Amount<input className="input w-full" type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Payment date<input className="input w-full" type="date" value={payment.payment_date} onChange={e=>setPayment({...payment,payment_date:e.target.value})}/></label><label>Mode<select className="input w-full" value={payment.payment_mode} onChange={e=>setPayment({...payment,payment_mode:e.target.value})}>{['Bank','UPI','Cheque','NEFT/RTGS','Cash'].map(m=><option key={m}>{m}</option>)}</select></label><label>Transaction reference<input className="input w-full" value={payment.transaction_ref} onChange={e=>setPayment({...payment,transaction_ref:e.target.value})}/></label></div><button disabled={busy||!canEdit('installation')} className="btn btn-primary" onClick={()=>action(()=>api.post(`/sales-billing/${detail.bill.id}/payment`,payment),'Collection recorded')}>Record collection</button></details></div>}
      <details><summary className="cursor-pointer">Bill activity</summary>{detail.events.map(e=><p className="text-xs py-1" key={e.id}>{e.created_at} · {e.event} · {e.detail} · {e.actor||'ERP'}</p>)}</details>
    </div>}</Modal>
  </div>;
}
